import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from '../components/nav'
import Subheader from '../components/subheader'
import {useEffect} from 'react'
import script from '../public/images/script.jpg'
import Post from '../components/post'
import Ship from '../components/ship'

function Home({posts, userAuth, updateUserAuth}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav text='Ye Olde Diary' userAuth={userAuth} updateUserAuth={updateUserAuth} />
      <div className={styles.welcomeWrapper}>
        <Subheader className={styles.subheaderDiv} text='Etchings From Premodernity' />
        <Ship className={styles.welcomeImagediv} />


      </div>
      <div className={styles.postsWrapper}>
        <div className={styles.postsHeader}>
          <h3>Volumes</h3>
        </div>
        <div className={styles.allPosts}>



        {posts.map((post, index) => (
          <Post key={index} post={post} />

        ))}

        </div>

        </div>



    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:5000/api/posts');
  const posts = await res.json();

  return{
    props:{
      posts,
    },
  }
}


export default Home
