import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Longtext from '../components/longtext'

function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hello world</h1>

        {posts.map((post) => (
        <div className={styles.card}>
          <h2> {post.title} </h2>
          <Longtext limit={20} content={post.content} />
        </div>
        ))}

      </div>

    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch('http://localhost:5000/api/posts');
  const posts = await res.json();

  return{
    props:{
      posts,
    },
  }
}


export default Home
