import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Subheader from '../components/subheader'
import Loginform from '../components/loginform'

function Register({posts, updateUserAuth}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ye Olde Diary | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <Loginform className={styles.container} updateUserAuth={updateUserAuth} />

        </div>



  )
}


export default Register
