import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Subheader from '../components/subheader'
import script from '../public/images/script.jpg'
import Registerform from '../components/registerform'

function Register({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ye Old Diary | Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon/favicon.ico" />
      </Head>

      <Registerform />

        </div>



  )
}


export default Register
